### PR TITLE
Fix Issue where maxing out Chrome Sync Storage

### LINKED ISSUE #20: Tabs stop grouping and moving to the beginning
Hey,
It's feeling a little buggy last days.

Tabs are still getting tagged but it no longer grouping by category and grouping at the begins.

behavior
wanted

### PR DESCRIPTION
**Pull request by bsell93**
Should fix #20

### CODE REVIEW

**Comment by bsell93** [comment]
There may be an issue with this change. I'm noticing my collapsed groups will uncollapse with no user interaction. Will need to investigate. Likely will need to make some modifications here to make sure the clearing of the group ids is once.

**Comment by bsell93** [comment]
I believe this will do the trick
https://stackoverflow.com/a/61328933/4965713

**Comment by jdhayford** [comment]
Good idea for a cleanup! One thing im worried about is will this cause a clearing if the user creates a new window of chrome? If so it will lead to somewhat jarring reordering of tabs (if that is the case of course). I'd be happy to test but it might take me a day or two before I can build and test.

**Comment by bsell93** [comment]
@jdhayford yes, that's how my original implementation was working. By using the `chromchrome.runtime.onStartup` listener I believe that is not a problem anymore.

Yes, please check out when you can and let me know if there are any issues!

**Pull request merged**
